### ISSUE TITLE
Add Chroot Support

### ISSUE THREAD

**Issue by WMCB-Tech** [WMCB-Tech/debdroid#16]
This can be done via unshare and chroot, and for rooted device only

**Comment by WMCB-Tech** [comment]
Seems i got invalid argument error when using 

```
unshare --fork --pid chroot <newroot> <cmd>
```
in AVD while in Linux Distributions, it does work

Although i need some other chroot garbage collect methods besides `unshare`

**Comment by suhan-paradkar** [comment]
@WMCB-Tech I guess you can test this now on your Andr12 AVD...

**Comment by WMCB-Tech** [comment]
Good idea

**Comment by WMCB-Tech** [comment]
Closing since i really don't have motivation to do it
