### ISSUE TITLE
debdroid-stop-server will not work if termux closed/crashed while debian is running

### ISSUE THREAD

**Issue by zekuzodia** [WMCB-Tech/DebDroid#2]
My termux closed itself while I was using debian and now it cant be launched without - cli, debdroid-stop-server will not fix the problem, you'll be forced to use --launch-cli, However this can be fixed by deleting the /.vnc/ folder located in /data/data/com.termux/files/home/

**Comment by WMCB-Tech** [comment]
The easiest way to fix it is to reboot your device. DebDroid Requires more fixes than Andronix

**Comment by WMCB-Tech** [comment]
@zekuzodia The `debdroid-stop-server` is now fixed at v2.13
