### ISSUE TITLE
Android 10 

### ISSUE THREAD

**Issue by ZhymabekRoman** [WMCB-Tech/DebDroid#4]
**Device Information**
Android OS: Android 10
Device Model:Samsung A10

On my phone, debdroid works fine

**Comment by WMCB-Tech** [comment]
Thanks. i'll label this as Android 10 and discussion

**Comment by WMCB-Tech** [comment]
So @ZhymabekRoman are there utilities are working: `netstat`, `ip addr`, or `ifconfig`

**Comment by ZhymabekRoman** [comment]
> So @ZhymabekRoman are there networking utilities working?: `netstat`, `ip addr`, or `ifconfig`. due to privacy changes:
> https://developer.android.com/about/versions/10/privacy/changes#proc-net-filesystem

Yes, work fine

**Comment by WMCB-Tech** [comment]
@ZhymabekRoman it seems i updated my Oppo phone to Android 10 and DebDroid works fine. so i might close this issue. however if you need more queries I'll reopen this issue
