### ISSUE TITLE
QEMU Support.

### ISSUE THREAD

**Issue by WMCB-Tech** [WMCB-Tech/DebDroid#5]
As DebDroid is designed for easy to use. we will support qemu but not yet implemented and is out of scope

By inspecting the DebDroid Code. you can see it needs to match the valid Architecture. and somehow needed to bypass it either QEMU Environment Variable or User Prompt. but causing unbound variable or somewhat I'm intermediate to this scripting. that would need to have Script-rewrite. causing to invalidate settings even export files

# Disadvantages
While QEMU Support allows to run Intel/x86 Programs there's some disadvantages as well. + PRoot disadvantages

* sudo problems - Errors about setuid 0
* instability of some binaries
* slow updating & upgrading even causing segfaults that would result to fail

# How to Help?
While i still figuring out how to implement this.
Contributions are welcome. you can download the source package and try to make changes to them

Alternatively is to create pull requests and I could make a branch to see if qemu implementation works well with your help

There are many ways to help

Any queries here are welcome

**Comment by gaberilde** [comment]
Army works fine for my end must be a kernal thing

**Comment by WMCB-Tech** [comment]
Nope. not about kernel. thinking of architecture emulation support. allowing to run wine on arm. or compiling stuff for arm. etc

**Comment by nakele** [comment]
Just tried this myself, I messed around your --install function to "force" i386 and --launch as well with -q and  qemu. So it works in other rootfs that I have outside debdroid however debdroid has a problem in the installation process. How did u manage to get past the installation? Did u import it from an x86 installation?

**Comment by WMCB-Tech** [comment]
@nakele You can see these lines of code

**Check Architecture** https://github.com/WMCB-Tech/DebDroid/blob/master/prefix-bin/debdroid#L139

**Comment by nakele** [comment]
@WMCB-Tech I'm really new to linux so pardon my ignorance , why not leverage $SUITE to match x86?

if [$SUITE == 'x86'] archurl="dist-i386"
else
`case `uname -m` in		aarch64|arm64)			archurl="dist-arm64v8" ;;		arm|armv7l|armv8l)			archurl="dist-arm32v7" ;;		amd64|x86_64)			archurl="dist-amd64" ;;		x86|i*86)			archurl="dist-i386" ;;		*)			echo "${RED}${BOLD}unknown architecture${NOATTR}"; exit 1 ;;	esac`

**Comment by WMCB-Tech** [comment]
Probably i could do this:

``
if [[ "$QEMU-INSTALL-ARCH" == "qemu-*' ]]; then
  export USE_QEMU_ENV="$QEMU-INSTALL-ARCH"
else
  export USE_QEMU_ENV=""
fi
```

The $SUITE is the argument for stable/oldstable/testing

**Comment by WMCB-Tech** [comment]
Also one thing the feature might break is isolated mode. qemu-user transparently binds /host-rootfs as host's partition so maybe it's low priority and still figuring out how to deny access of it

**Comment by WMCB-Tech** [comment]
Moving this Discussion to GitHub Disscussion, Please use the Discussion tab
